# Generated by Django 4.1.5 on 2023-01-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zing_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.CharField(max_length=50),
        ),
    ]
