# Generated by Django 4.1.5 on 2023-01-14 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
